FROM python:3.8.18-bullseye
WORKDIR /app

COPY ./requirement.txt /app/requirement.txt
RUN pip install -r /app/requirement.txt

RUN wget https://github.com/jesseduffield/lazygit/releases/download/v0.40.1/lazygit_0.40.1_Linux_x86_64.tar.gz -O lazygit.tar.gz
RUN tar xf lazygit.tar.gz lazygit
RUN install lazygit /usr/local/bin
RUN rm lazygit.tar.gz lazygit

COPY . .

# create ssh key dir for git
COPY ./id_rsa ./
RUN mkdir -p /root/.ssh
RUN cp id_rsa /root/.ssh/
RUN chmod 600 /root/.ssh/id_rsa

EXPOSE 18090
CMD [ "bash", "-c", "while true; do sleep 1000; done;"]
