FROM python:3.11.5-bullseye
WORKDIR /app

COPY ./ /app/
RUN pip install -r /app/requirement.txt

RUN wget https://github.com/jesseduffield/lazygit/releases/download/v0.40.1/lazygit_0.40.1_Linux_x86_64.tar.gz -O lazygit.tar.gz
RUN tar xf lazygit.tar.gz lazygit
RUN install lazygit /usr/local/bin

CMD [ "bash" , "while true; do sleep 1000; done;"]
